### ISSUE TITLE
Enforce HTTPS?

### ISSUE THREAD

**Issue by andrewdotn** [whichjdk/whichjdk.com#17]
Hi, thanks for making this site, it really helps sort through the options!

Might I suggest [enforcing HTTPS](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https) for the site? It should be just [a few clicks](https://github.com/whichjdk/whichjdk.com/settings/pages) and will reduce risk a little bit for people visiting the site who will then be clicking links to download JDKs.

**Comment by jochenchrist** [comment]
Hi andrewdotn!
Thanks for your nice feedback.

I gladly activated "Enforce HTTPS" :)

BTW which version of JDK are you using now?
