### ISSUE TITLE
Add ojdkbuild

### ISSUE THREAD

**Issue by Crystal-RainSlide** [whichjdk/whichjdk.com#19]
https://github.com/ojdkbuild/ojdkbuild

Other than their readme, also see: https://github.com/ojdkbuild/ojdkbuild/wiki/Motivation

**Comment by jochenchrist** [comment]
Thanks for your contribution.

I added ojdkbuild in https://github.com/whichjdk/whichjdk.com/commit/de883e0b80b56787ecb97bb6ac962571fdf21924
