### ISSUE TITLE
which i use on windows?

### ISSUE THREAD

**Issue by hingbong** [whichjdk/whichjdk.com#20]
which i use on windows, includes server, how about microsoft builds?

**Comment by jochenchrist** [comment]
My general (opinionated) recommendation for Windows and Windows server is:
- Use Ensure to use the same version of the JDK for dev, CI, and production
- Use version 17, as it has LTS
- Use Adoptium Eclipse Temurin, as it has support by major industry and non-profit contributors, including Microsoft
- Nothing wrong with Microsoft Build of OpenJDK. If you choose these builds, these are perfectly fine as well.

**Comment by hingbong** [comment]
> My general (opinionated) recommendation for Windows and Windows server is:
> 
>     * Use Ensure to use the same version of the JDK for dev, CI, and production
> 
>     * Use version 17, as it has LTS
> 
>     * Use Adoptium Eclipse Temurin, as it has support by major industry and non-profit contributors, including Microsoft
> 
>     * Nothing wrong with Microsoft Build of OpenJDK. If you choose these builds, these are perfectly fine as well.

thank you
