### ISSUE TITLE
Add reasoning for recommendations

### ISSUE THREAD

**Issue by jansu76** [whichjdk/whichjdk.com#21]
What a lovely resource!

Some of the recommendations are without written out reasoning or rationale. For example _Alibaba Dragonwell_ has a "red stop sign" with "Do not use unless you are forced"....and _Red Hat OpenJDK_ has a "yellow warning" with "Use only if you are running on RHEL".

I would probably agree with those recommendations, but have only a really fuzzy thought process behind that. _Alibaba_...well I have never heard anyone using it, and it's Chinese, so it sounds a bit iffy. _Red Hat_....well, don't know much about that, to be honest I have no idea if it's better or worse option that e.g. Corretto.

I can only guess if you just went through a similar fuzzy thought process or if you had some specific points about _Alibaba_, _Red Hat_, _Microsoft_, etc that mean those should be avoided. It would be nice to see what the basis for not-recommending some options were, if I am sometimes in a position where I need to consider _Microsoft Build of OpenJDK_, _Alibaba_, _Red Hat OpenJDK_, etc. Even if reason is simply "there are more established options out there" or "I don't know enough of this one", it can be useful to know see that that's the basis of the recommendation.

**Comment by jochenchrist** [comment]
Fair point.
I just added "There are more established options available." to some options.

I will extend reasoning next time I iterate options.
