### ISSUE TITLE
About SDKMan

### ISSUE THREAD

**Issue by mattthebig** [whichjdk/whichjdk.com#27]
Just Feedback: I love that SDKMan makes it very easy to install java but I think jenv deserves recognition here.

SDKMan unfortunately has a very wide scope which mean it provides easy ways to do things that are actually harmful (installing gradle to the path). jenv's setup is heaps uglier `brew install corretto17 && jenv add /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/` [MacOS], but in some contexts (I'm thinking about my work in a large company) that's outweighed by jenv not being a general purpose tool (see tfenv, nvm etc.).

asdf is another contender in the space but I don't have much detail as we had trouble with it conflicting with NVM and not supporting legacy versions we needed.

Anyways in general - list is great! More reasoning/why nots in the version management space would make it even better. 
Hit me up if you would like input on any changes this prompts, or want me to draft something.

**Comment by jochenchrist** [comment]
Thanks for sharing your thoughts! I appreciate your feedback. 
I don't have direct experience with these tools, and for simplicity I decided not to add these tools for simplicity.
