### ISSUE TITLE
Use warning symbol for semuru recommendation

### ISSUE THREAD

**Issue by danthe1st** [whichjdk/whichjdk.com#31]
When viewing the https://whichjdk.com/, I can see that an ⚠️-emoji is normally used for recommendations that depend on the use-case.

However, [IBM Semeru Runtime](https://whichjdk.com/#ibm-semeru-runtime) uses a ⛔️-emoji even though the recommendation states
>  Use _IBM Semeru Runtime_ only if you know that you need the OpenJ9 Virtual Machine.

I think this recommendation for IBM Semeru Runtime should use the emoji ⚠️.

**Comment by jochenchrist** [comment]
Thanks for your contribution. Updated semuru to ⚠️
