### ISSUE TITLE
Need help to run Java (portable version) on a shared hosting with terminal (no root)

### ISSUE THREAD

**Issue by HGStyle** [whichjdk/whichjdk.com#32]
Hello,
I need some help.
I tried many JDKs (Termurin JDKs, RedHat JDKs and Microsoft JDKs) but none of them works...
I'm trying to run Java on a shared hosting with terminal access, but no root access.
Portable version of softwares can be used without root, that what I wanted to do.
But, any version I run has issues. Here are the common messages gaven:
 - `Segmentation fault (core dumped)`
 - `No such file or directory` (even if the file appears in `ls -l`, it seems like a library is missing so it shows this)

The server seems to be running on RHEL8 x86_64. You probably do not know the host I use, it's called o2switch.
It's a French hosting service, since I'm French, I'm using it, even if its not a VPS, I have terminal access, lots of "computer power" (like 48Gb RAM, "Unlimited" NVMe SSD, etc...). I asked them for help 2 times, because the error was not only for Java but for every prebuilt binaries I downloaded (I tried ffmpeg, p7zip and they gave the same error, but this time only `Segmentation fault (core dumped)`, also it seems that when building the software from source on the server it works, I tested with p7zip, but since OpenJDK has lots of requirements and almost nothing is installed on the server, I'm asking for help first).
They said (I translated from French to English for you): "The binaries are not correct." about ffmpeg (because I built it manually) and specifically for Java: "Java is not available on our hosting service." (I actually asked for Java access).
Any ideas why it does not works ?

**Comment by jochenchrist** [comment]
Running Java on a shared hosting environment without proper support and root access can be difficult due to compatibility issues, missing dependencies, and limited control over the server.

Running Java and other binaries as Docker container might be a solution, if Docker is available.
