### ISSUE TITLE
Recommendation is not yet available

### ISSUE THREAD

**Issue by truj** [whichjdk/whichjdk.com#33]
> ✅ Recommendation: Use [Adoptium Eclipse Temurin 21](https://whichjdk.com/#adoptium-eclipse-temurin) and ensure that your local version matches the CI and production version.

Well, version 21 is not yet available. According to [their website](https://adoptium.net/de/support/), it's expected to come out this month but today it's not possible to download.
So how can this version already be recommended?

**Comment by jochenchrist** [comment]
Sorry, my bad. Updated.
It may take a few days until all distributions released the package in all versions.
