### ISSUE TITLE
JDK LTS Cadence

### ISSUE THREAD

**Issue by hink084** [whichjdk/whichjdk.com#35]
> Every three years, the September release will be a Long-Term-Support (LTS) release, which gets updates for at least three years.

Oracle proposed a shorter LTS release cycle from three years to two years in 2021.  So a LTS release will occur every four versions instead of every six - JDK 21 instead of JDK 23.

[https://blogs.oracle.com/java/post/moving-the-jdk-to-a-two-year-lts-cadence](https://blogs.oracle.com/java/post/moving-the-jdk-to-a-two-year-lts-cadence)

[https://mreinhold.org/blog/forward-even-faster](https://mreinhold.org/blog/forward-even-faster)

**Comment by jochenchrist** [comment]
Thanks for the contribution, I will update the page accordingly

**Comment by jochenchrist** [comment]
Updated accordingly.
