### ISSUE TITLE
Some links are in German, also some language fixes for Korean links

### ISSUE THREAD

**Issue by yetisyny** [whichjdk/whichjdk.com#38]
The links to Amazon Corretto link to https://aws.amazon.com/de/corretto/ instead of https://aws.amazon.com/en/corretto/, so they are in German instead of English. Both the Website and Releases links are in German, but the Docker Images link and images in the part describing Amazon Corretto are already in English so that is fine. Also there is a link to https://www.oracle.com/de/downloads/licenses/binary-code-license.html for the Oracle Binary Code Agreement in German instead of the English link https://www.oracle.com/downloads/licenses/binary-code-license.html

Anyway, it would be best to replace these with the English links. So that above part of this issue is for German-language websites being linked from both English and Korean versions of your site, something that should be fixed.

The rest of this post concerns the Korean version of your site using the same exact links as the English version.

The Korean version of the site uses the same links as the English version of the site. Some of these can be replaced with Korean-language links.

The official OpenJDK website, wcsp website, Adoptium Eclipse Temurin website, Docker website, AdoptOpenJDK website, Bellsoft Liberica website, IBM developer website, Eclipse website, Github website, Alibaba Dragonwell website, SapMachine website, Red Hat OpenJDK website, GraalVM, SDKMAN website, Spring Boot website, Micronaut website, and Quarkus website all either do not have Korean versions or use the same URLs for other languages, so there is no need for other links for other languages.

But the Oracle and Amazon websites have full Korean versions while the Azul Zulu / Azul Zing website and Microsoft website have only some pages available in Korean but not others. So the 4 websites that have at least some Korean webpages with different URLs are Oracle, Amazon, Azul, and Microsoft. The rest of the websites linked do not need anything done for Korean users.

So replace https://www.oracle.com/java/technologies/java-se-support-roadmap.html with https://www.oracle.com/kr/java/technologies/java-se-support-roadmap.html, https://www.oracle.com/java/ with https://www.oracle.com/kr/java/, https://www.oracle.com/java/technologies/downloads/archive/ with https://www.oracle.com/kr/java/technologies/downloads/archive/, https://www.oracle.com/de/downloads/licenses/binary-code-license.html with https://www.oracle.com/kr/downloads/licenses/binary-code-license.html, https://www.oracle.com/downloads/licenses/javase-license1.html with https://www.oracle.com/kr/downloads/licenses/javase-license1.html, https://www.oracle.com/downloads/licenses/no-fee-license.html with https://www.oracle.com/kr/downloads/licenses/no-fee-license.html on the Korean version of the page. The pattern for all of these oracle.com links is /kr/ after oracle.com for the Korean version of the page, while you leave a language code out for the English version of the page.

For Azul Zulu / Azul Zing, replace https://www.azul.com/ with https://www.azul.com/ko/ for the main webpage in Korean, but keep the webpages https://www.azul.com/downloads/?package=jdk#download-openjdk and https://www.azul.com/products/prime-roadmap/ the same as they are only available in English.

For Amazon Corretto, replace https://aws.amazon.com/de/corretto/ with https://aws.amazon.com/ko/corretto/ and https://aws.amazon.com/corretto/faqs/ with https://aws.amazon.com/ko/corretto/faqs/ and https://aws.amazon.com/blogs/opensource/introducing-amazon-corretto-crypto-provider-accp/ with https://aws.amazon.com/ko/blogs/opensource/introducing-amazon-corretto-crypto-provider-accp/ for the Korean webpages. The pattern for all of these aws.amazon.com links is /ko/ after aws.amazon.com for the Korean version of the page, while you leave a language code out for the English version of the page.

For Microsoft Build of OpenJDK, keep https://www.microsoft.com/openjdk the same because the main www.microsoft.com website uses the same URLs for all languages. But replace https://docs.microsoft.com/en-us/java/openjdk/download with https://learn.microsoft.com/ko-kr/java/openjdk/download for the Korean webpage on docs.microsoft.com.

That is everything, as far as showing people links in the correct language whenever possible. You do not need to replace any of the text displayed on the webpage in either English or Korean as far as this issue is concerned, only URLs for links that it links to. So you do not need to know any Korean to replace those URLs, you can leave the text of the page unchanged and just replace certain URLs, and note for the future that Oracle, Azul, Amazon, and Microsoft have different URLs on their webpages depending on the language, while the other websites you link to either do not, or do not include Korean as a language option.

**Comment by jochenchrist** [comment]
Thanks for this report. I fixed the Coretto links.
